[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[dependencies]
ens-contracts-main = { version = "v1.0.0", git = "https://github.com/ensdomains/ens-contracts.git", rev = "87d8cc5778d483e2b4094868eec0c0cfc9e36a90" }
ens-contracts-urv3 = { version = "v1.0.0", git = "https://github.com/ensdomains/ens-contracts.git", rev = "9a89be3d31ccb1f4d0e9c6c5a2e2ededf3aa990a" }
"@openzeppelin/contracts" = { version = "v4.8.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "49c0e4370d0cc50ea6090709e3835a3091e33ee2" }
"@openzeppelin/contracts-sup" = { version = "v5.2.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "840c974028316f3c8172c1b8e5ed67ad95e255ca" }
"@openzeppelin/contracts-upgradeable" = { version = "v5.2.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", rev = "7f47eb4df9cf70306cc167f4d655275d94dda7cc" }

[profile.soldeer]
remappings_regenerate = false
